apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
        role: master
    spec:
      containers:
      - name: redis
        image: amydocker/redis-sentinel
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "1"
            memory: "6656M"
          requests:
            cpu: "1"
            memory: "6656M"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
